package client.core;

public enum InterfaceEnum
{
    LOGIN,
    MANAGER_EMPLOYEE,
    MANAGER_WARD,
    SHARED_PATIENT,
    DOCTOR_SAMPLE,
    DOCTOR_TREAT_UPDATE,
    DOCTOR_NURSE,
    SHARED_APPOINTMENT,
    NURSE_PATIENT,
    NURSE_APPOINTMENT,
    SHARED_EMPLOYEE
}
